# Generated by Django 3.2.5 on 2022-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(null=True),
        ),
    ]
