# Generated by Django 3.2.5 on 2022-07-23 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20220718_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 9, 21, 33, 607154, tzinfo=utc)),
        ),
    ]
